const ciudadesPorDepartamento = {
  "Amazonas": ["Leticia", "Puerto Narino"],
  "Antioquia": ["Medellin", "Bello", "Envigado", "Itagui", "Apartado", "Rionegro", "Turbo", "Carepa", "Copacabana", "Girardota"],
  "Arauca": ["Arauca", "Saravena", "Tame"],
  "Atlantico": ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Galapa"],
  "Bolivar": ["Cartagena", "Magangue", "Turbo", "Mompos", "El Carmen de Bolivar"],
  "Boyaca": ["Tunja", "Duitama", "Sogamoso", "Chiquinquira", "Paipa"],
  "Caldas": ["Manizales", "La Dorada", "Chinchina", "Villamaria", "Aguadas"],
  "Caqueta": ["Florencia", "San Vicente del Caguan", "Albania", "El Doncello"],
  "Casanare": ["Yopal", "Aguazul", "Villanueva", "Tauramena", "Paz de Ariporo"],
  "Cauca": ["Popayan", "Santander de Quilichao", "Patia", "Puerto Tejada", "Guapi"],
  "Cesar": ["Valledupar", "Aguachica", "La Jagua de Ibirico", "Bosconia", "Codazzi"],
  "Choco": ["Quibdo", "Nuqui", "Istmina", "Tado", "El Carmen de Atrato"],
  "Cordoba": ["Monteria", "Sahagun", "Lorica", "Planeta Rica", "Tierralta"],
  "Cundinamarca": ["Bogota", "Soacha", "Girardot", "Facatativa", "Zipaquira"],
  "Guainia": ["Inirida", "Barranco Minas"],
  "Guaviare": ["San Jose del Guaviare"],
  "Huila": ["Neiva", "Pitalito", "Garzon", "Campoalegre", "La Plata"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure", "Dibulla"],
  "Magdalena": ["Santa Marta", "Cienaga", "Fundacion", "Aracataca", "Plato"],
  "Meta": ["Villavicencio", "Acacias", "Granada", "Puerto Lopez", "Puerto Gaitan"],
  "Narino": ["Pasto", "Tumaco", "Ipiales", "Tuquerres", "El Charco"],
  "Norte de Santander": ["Cucuta", "Ocana", "Pamplona", "Los Patios", "Villa del Rosario"],
  "Putumayo": ["Mocoa", "Puerto Asis", "Orito", "La Hormiga", "Sibundoy"],
  "Quindio": ["Armenia", "Calarca", "Montenegro", "La Tebaida", "Circasia"],
  "Risaralda": ["Pereira", "Dosquebradas", "La Virginia", "Santa Rosa de Cabal", "Belén de Umbria"],
  "San Andres y Providencia": ["San Andres"],
  "Santander": ["Bucaramanga", "Floridablanca", "Giron", "Piedecuesta", "Barrancabermeja"],
  "Sucre": ["Sincelejo", "Corozal", "Santiago de Tolú", "San Marcos", "Morroa"],
  "Tolima": ["Ibague", "Espinal", "Mariquita", "Chaparral", "Lerida"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tulua", "Yumbo"],
  "Vaupes": ["Mitu", "Caruru"],
  "Vichada": ["Puerto Carreno", "La Primavera"]
};

module.exports = ciudadesPorDepartamento;
